### Add a new junk shop product
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Scrap Iron",
  "image": "https://example.com/images/scrap-iron.jpg",
  "category": "Metal",
  "purchasePrice": 10.50,
  "sellingPrice": 15.00,
  "quantity": 200,
  "unit": "kgs",
  "description": "Collected scrap iron from construction sites."
}


### Add used aluminum cans
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Used Aluminum Cans",
  "image": "https://example.com/images/aluminum-cans.jpg",
  "category": "Metal",
  "purchasePrice": 5.00,
  "sellingPrice": 8.00,
  "quantity": 500,
  "unit": "pcs",
  "description": "Cleaned and sorted aluminum cans from residential areas."
}


### Get all products
GET http://localhost:3000/products


### Get a single product by ID
GET http://localhost:3000/products/68deb602befb244f000625f9



### Get a single product by ID
GET http://localhost:3000/products/68deb5f5befb244f000625f7


### Update a product by ID
PATCH http://localhost:3000/products/68deb5f5befb244f000625f7
Content-Type: application/json

{
  "name": "Updated Scrap Iron",
  "image": "https://example.com/images/updated-scrap-iron.jpg",
  "category": "Metal",
  "purchasePrice": 12.00,
  "sellingPrice": 18.00,
  "quantity": 150,
  "unit": "kgs",
  "description": "Updated description for scrap iron."
}


### Delete a product by ID
DELETE http://localhost:3000/products/68deb5f5befb244f000625f7

